### PR TITLE
regex in the wrong spot

### PR DESCRIPTION
**Pull request by metric152**
When I pull down your code I get an error when trying to import scripts into the worker. I moved the added regex check to the only spot it's used and now it works properly.

### CODE REVIEW

**Comment by metric152** [comment]
bump

**Comment by cdsanchez** [comment]
Do you recall what the error was? Curious that it was causing an error in one place but not another. Worried that it just might be deferring the error (though if it was a syntax error, it would fail on parse..).

Thanks!

**Comment by metric152** [comment]
It failed when I tried including a remote bit of code as an import. Here's an example that failed with the current code. 

https://github.com/metric152/advent-of-code/blob/master/day-4/code.js

**Comment by cdsanchez** [comment]
Ah I see, it was scoped incorrectly. Thanks for the PR!

**Comment by metric152** [comment]
No prob. Thanks for making the lib. It was pretty hard to try and find a social link to get your attn. Glad the bump worked.

**Pull request merged**
